name: Creating docker image and deploying it docker hub

on:
  push:
    branches: [ main]

jobs:

  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
           docker build .  -t mcncyo/hugo-builder:latest
      - name: publish
        run: |
          docker login -u mcncyo -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push mcncyo/hugo-builder:latest


          
